[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fastapi-jwt2"
version = "0.1.0"
description = "A fork of libre-fast-jwt that uses Pydantic V2"
authors = ["cblgn <plcblgn+github@gmail.com>"]
license = "MIT"
repository = "https://github.com/cblgn/fastapi_jwt2"
readme = "README.md"
classifiers = [
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.10"
PyJWT = "^2.8.0"
fastapi = "^0.110.0"

[tool.poetry.dev-dependencies]
pytest = "^8.0.1"
requests = "^2.31.0"
pytest-cov = "^4.1.0"
uvicorn = "^0.27.0"
mkdocs = "^1.5.3"
markdown-include = "^0.8.1"
mkdocs-material = "^9.5.11"
httpx = ">=0.27.0"
pydantic-settings = ">=2.2.1"
black = "^24.2.0"